print("Hello world")
print("does this work")
print("This is new")
print("This time I'll try Commit and Push")
print("The previous print statement had an error, I fixed it")
print("Now I'm trying to use the updates in the upper right hand corner")